IG-19957 adding master role to kubernetes
iguazio/kubespray pull request #64
Opened 2022-01-03 13:07 UTC by yuribros1974

IG-19957 adding master role to kubernetes

2022-01-03 13:16 UTC, yuribros1974 commented
Creating package of kubespray that include that change: https://jenkins-prod.iguazeng.com/job/kubespray/job/IG-19957_update_igz_offline/2/console
After that will create dedicated build that include that package, after that will build env with that

2022-01-04 17:34 UTC, alexpirogovski requested changes
roles/download/templates/kubeadm-images.yaml.j2
I would add a HUGE comment here so I don't forget to carry it to the next upstream update

2022-01-04 17:42 UTC, alexpirogovski commented on roles/download/templates/kubeadm-images.yaml.j2
> +  imageTag: v1.8.0
Should be taken from
https://github.com/iguazio/kubespray/blob/bbd0ade6f7ede7b3106097223fdb7bc35ff98c77/roles/igz_offline/defaults/main.yml#L12

2022-01-09 14:35 UTC, yuribros1974 commented
was tested on: https://jenkins-prod.iguazeng.com/job/customer_deploy/job/integ_3.2/347/
with kubespray: https://jenkins-prod.iguazeng.com/job/kubespray/job/IG-19957_update_igz_offline/6/
and build: https://jenkins-prod.iguazeng.com/job/build/job/development/1641/

2022-01-09 14:37 UTC, uriblum46 approved these changes

2022-01-09 14:40 UTC, merged